# Dockerfile.main

FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    poppler-utils \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY models/all-MiniLM-L6-v2 /app/models/all-MiniLM-L6-v2

RUN mkdir -p /app/input /app/output /app/output2

CMD ["python", "main.py"]
